name: Deploy Docs

on:
  push:
    branches:
      - mother
    tags:
      - v*
    paths-ignore:
      - "CHANGELOG.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Install system libsodium
        run: |
          sudo apt-get update
          sudo apt-get install -y libsodium

      - name: Install shard dependencies
        run: shards install

      - name: Generate docs
        run: crystal doc

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          destination_dir: ${{ steps.extract_branch.outputs.branch }}
          enable_jekyll: false